name: Setup environment variables and publish a Docker image to ECR

on:
  workflow_call:
    inputs:
      release-type:
        description: 'The release type, "branch" if its a PR or "release" if its main or a release branch'
        required: false
        type: string
        default: branch
      dev-env:
        description: 'The environment used for the dev deployment, for auto-approved deployments please use an empty string ""'
        required: false
        type: string
        default: dev
env:

  # This value is summed to the workflow run_number to calculate the
  # tag_number, and it's added to count for the CircleCI images published to
  # ECR.
  TAG_OFFSET: 12183
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  
  env-var:
    name: Setup environment variables
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Tag number
        id: tag-number
        run: |
          tag_number=$((${{ env.TAG_OFFSET }} + ${{ github.run_number }}))
          echo "tag_number=${tag_number}" >> $GITHUB_OUTPUT
      - name: Image name
        id: image-name
        run: |
          tag_number=$((${{ env.TAG_OFFSET }} + ${{ github.run_number }}))
          echo "image_tag=${{ env.BRANCH_NAME }}-${tag_number}" >> $GITHUB_OUTPUT
            
    outputs:
      TAG_NUMBER: ${{ steps.tag-number.outputs.tag_number }}
      IMAGE_TAG: ${{ steps.image-name.outputs.image_tag }}
      ECR_REPOSITORY_NAME: Repo-name
      ECR_HOSTNAME: Hostname

      ECR_PROD_ROLE: Prod-Role

      ECS_BETA_ROLE: Beta-Role
      ECS_STAGE_ROLE: Stage-Role
      ECS_PROD_ROLE: Prod-Role

  docker-build-and-push-ecr:
    name: Build a Docker image and publish to ECR
    needs: env-var
    uses: ./.github/workflows/push-to-repo.yml
    with:
      image-tag: ${{ needs.env-var.outputs.IMAGE_TAG }}

  beta-pre-release:
    if: inputs.release-type != 'main'
    name: Beta environment Pre release commnad
    needs: [env-var, docker-build-and-push-ecr]
    uses: ./.github/workflows/deploy.yml
    with:
      image-tag: "${{ needs.env-var.outputs.IMAGE_TAG }}-dev-pre-release-WAIT-rollback"
      environment: beta

  beta-deploy:
    if: inputs.release-type != 'main'
    name: Deploy to ECS from Beta environment
    needs: [env-var, docker-build-and-push-ecr]
    uses: ./.github/workflows/deploy.yml
    with:
      image-tag: "${{ needs.env-var.outputs.IMAGE_TAG }}-dev-deploy"
      environment: beta

  stage-pre-release:
    if: inputs.release-type == 'main' || inputs.release-type == 'branch' 
    name: Stage environment Pre release commnad
    needs: [env-var, docker-build-and-push-ecr]
    uses: ./.github/workflows/deploy.yml
    with:
      image-tag: "${{ needs.env-var.outputs.IMAGE_TAG }}-stage-pre-release-WAIT-rollback"
      environment: stage

  stage-deploy:
    if: inputs.release-type == 'main' || inputs.release-type == 'branch' 
    name: Deploy to ECS from Stage environment
    needs: [env-var, docker-build-and-push-ecr]
    uses: ./.github/workflows/deploy.yml
    with:
      image-tag: "${{ needs.env-var.outputs.IMAGE_TAG }}-stage-deploy"
      environment: stage

  prod-pre-release:
    if: inputs.release-type == 'main'
    name: Prod environment Pre release commnad
    needs: [env-var, docker-build-and-push-ecr]
    uses: ./.github/workflows/deploy.yml
    with:
      image-tag: "${{ needs.env-var.outputs.IMAGE_TAG }}-prod-pre-release-WAIT-rollback"
      environment: prod

  prod-deploy:
    if: inputs.release-type == 'main'
    name: Deploy to ECS from Prod environment
    needs: [env-var, docker-build-and-push-ecr]
    uses: ./.github/workflows/deploy.yml
    with:
      image-tag: "${{ needs.env-var.outputs.IMAGE_TAG }}-prod-deploy"
      environment: prod
