name: Push to repo

on:
  workflow_call:
    inputs:
      image-tag:
        required: true
        description: 'Image tag'
        type: string
      runs-on:
        required: false
        type: string
        default: "['ubuntu-latest']"



jobs:
  push-repo:
    name: Push Repo
    runs-on: ${{ fromJSON(inputs.runs-on) }}
    steps:
      - name: Print Image Tag
        shell: bash
        run: |
          echo '"Created" image ${{ inputs.image-tag }}'
